package com.megadevs.adoma;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import com.megadevs.adoma.AdomaKey;

import com.megadevs.adoma.AdomaKeyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig adomaKeyDaoConfig;

    private final AdomaKeyDao adomaKeyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        adomaKeyDaoConfig = daoConfigMap.get(AdomaKeyDao.class).clone();
        adomaKeyDaoConfig.initIdentityScope(type);

        adomaKeyDao = new AdomaKeyDao(adomaKeyDaoConfig, this);

        registerDao(AdomaKey.class, adomaKeyDao);
    }

    public void clear() {
        adomaKeyDaoConfig.getIdentityScope().clear();
    }

    public void deleteAllData() {
        adomaKeyDao.deleteAll();
    }


    public AdomaKeyDao getAdomaKeyDao() {
        return adomaKeyDao;
    }

}
